version: '3.8'

services:
  back:
    build: ./back
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  front:
    build: ./front
    ports:
      - "5173:5173"
